[package]
name = "checksum-ricorsivo"
version = "0.1.0"
edition = "2021"

[dependencies]
crc = "3.2.1"
hex = "0.4.3"
hex-literal = "1.0.0"
md-5 = "0.10.6"
num_cpus = "1.16.0"
walkdir = "2.5.0"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
